require 'google/api_client/client_secrets'
require 'googleauth'
require 'google/apis/calendar_v3'

Rails.configuration.tap do |config|
    config.google = {
        :production => {
            :secret => "...",
            :identifier => "..."
        },

        :development => {
            :secret => "...",
            :identifier => "..."
        }
    }

    config.google_encode = "..."

    config.google_api_key = "..."

    config.oauth2_client_secrets = {
        youtube: Google::APIClient::ClientSecrets.new(
            'web' => {
                client_id: "xxx.apps.googleusercontent.com",
                client_secret: "...",
                redirect_uri: "...",
                javascript_origin: "...",
            }
        ),
    }
end

module GOOGLE
    extend self

    # TODO: Gem updated, clients no longer generically constructed.
    # CLIENT = new_client
    # KEY_CLIENT = new_client(key: true)
    # YOUTUBE = KEY_CLIENT.discovered_api('youtube', 'v3')

    # Generated by Google when you make a new service account.
    if File.file?(file = 'config/google.json')
      service_auth = Google::Auth::ServiceAccountCredentials.make_creds(
        json_key_io: File.open(file),
        scope: Google::Apis::CalendarV3::AUTH_CALENDAR_READONLY)
      service_auth.fetch_access_token!
      CALENDAR = Google::Apis::CalendarV3::CalendarService.new
      CALENDAR.authorization = service_auth
    end
end
